server:
  port: 8080

resilience4j:
  ratelimiter:
    instances:
      mailServiceRateLimit:
        # 기간(limitRefreshPeriod) 동안 허용되는 호출 수
        limitForPeriod: 10 # 예: 60초에 10개 요청
        # 제한을 재설정하는 주기
        limitRefreshPeriod: 60s # 예: 60초
        # 호출 허용을 기다리는 최대 시간 (0이면 즉시 실패)
        timeoutDuration: 0 # 예: 대기 없이 즉시 실패
  bulkhead:
    instances:
      mailServiceBulkhead:
        # 동시에 허용되는 최대 호출 수
        maxConcurrentCalls: 3 # 예: 최대 3개 동시 호출 허용
        # 동시 호출 수가 꽉 찼을 때 대기하는 최대 시간 (0이면 즉시 실패)
        maxWaitDuration: 0 # 예: 대기 없이 즉시 실패

spring:
  kafka:
    # Docker Compose에 설정된 외부 접속 포트 리스트
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    producer:
      # 메시지 키와 값의 직렬화 방식 (필요에 따라 변경)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # ▼▼▼ 메시지에 타입 헤더 추가 안 함 설정 ▼▼▼
        spring.json.add.type.headers: false
